manifest.version=0.2
target.sdk=0.8.0-C5-dev
target.platforms=esp32p4,esp32c5
app.id=tactility.espnowbridge
app.version.name=0.9.0
app.version.code=9
app.name=ESP-NOW Bridge
app.description=Companion app for updating P4 device C6 co-processor firmware to enable ESP-NOW bridge support.
