manifest.version=0.2
target.sdk=0.8.0
target.platforms=esp32c5
app.id=tactility.twoeleven
app.version.name=0.14.0
app.version.code=14
app.name=2048
app.description=A fun, customizable 2048 sliding tile game for tactility!\nSlide tiles to combine numbers and reach 2048.\nChoose grid sizes: 3x3 (easy), 4x4 (classic), 5x5, or 6x6 (expert).
