manifest.version=0.2
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4,esp32c5
app.id=tactility.breakout
app.version.name=0.14.0
app.version.code=14
app.name=Breakout
app.description=Classic brick-breaking arcade game
