manifest.version=0.2
target.sdk=0.8.0-dev
target.platforms=esp32p4,esp32c5
app.id=tactility.doom
app.version.name=0.5.0
app.version.code=5
app.name=Doom
app.description=Classic DOOM. Tab5 only, keyboard required to play.
requires.device.id=m5stack-tab5
