manifest.version=0.2
target.sdk=0.8.0
target.platforms=esp32s3,esp32p4,esp32c5
app.id=tactility.mediakeys
app.version.name=0.12.0
app.version.code=12
app.name=Media Keys
app.description=Bluetooth media keys. Touch or Physical Keyboard control\nB - previous, P - play/pause, N - next, M - mute, D - volume down, U - volume up.\nQ or ESC to exit focus.
